---
- name: create /var/run/gpustatd
  file:
    path: /var/run/gpustatd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install gpustatd
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gpustatd

- name: install gpustatd config
  copy:
    src: gpustatd.conf
    dest: /etc/gpustatd.conf
    owner: root
    group: root
    mode: 0644

- name: enable gpustatd service
  systemd:
    name: excavator
    enabled: true