---
- name: install gpustatsd
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gpustatsd

- name: install gpustatsd config
  copy:
    src: gpustatsd.conf
    dest: /etc/gpustatsd.conf
    owner: root
    group: root
    mode: 0644

- name: enable gpustatsd service
  systemd:
    name: excavator
    enabled: true