---
- name: add mainline kernel repository
  yum_repository:
    name: mainline-kernel
    description: Mainline Kernel
    baseurl: http://ftp.redsleeve.org/pub/misc/kernel/x86-64/RPMS/
    gpgcheck: no
    enabled: yes

- name: install epel
  yum:
    name: epel-release
    state: present

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim-enhanced
  - pv
  - wget
  - lynx
  - telnet
  - kernel-headers
  - xorg-x11-server-Xorg
  - gdm
  - alien
  - dkms
  - screen
  - pciutils
  - mc
  - ack
  - ccze
  - deltarpm
  - htop

- name: yum update
  yum:
    name: '*'
    state: latest

- name: create hugetlb group
  group:
    name: hugetlb
    state: present

- name: enable gdm graphical target
  shell: /bin/systemctl set-default graphical.target

- name: set tuned-adm throughput-performance
  shell: /usr/sbin/tuned-adm profile throughput-performance

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: update /etc/environment
  lineinfile:
    create: yes
    backup: yes
    dest: /etc/environment
    state: present
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^LANG=', line: 'LANG=en_US.utf-8' }
    - { regexp: '^LC_ALL=', line: 'LC_ALL=en_US.utf-8' }
    - { regexp: '^NO_AT_BRIDGE=', line: 'NO_AT_BRIDGE=1' }

# Blacklist the nouveau driver module
- kernel_blacklist:
    name: nouveau
    state: present