---
- name: install minotaur
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - minotaur

- name: install minotaur config
  template: 
    src: minotaur.conf.j2
    dest: /etc/minotaur.conf
    owner: root
    group: root
    mode: 0644

- name: install minotaur convenience commands
  copy:
    src: '{{ item.src }}'
    dest: '/usr/local/bin'
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: 'gs' }
    - { src: 'stats' }
    - { src: 'algos' }
    - { src: 'minlog' }
    - { src: 'fanlog' }
    - { src: 'exclog' }
    - { src: 'excwraplog' }

#- name: enable minotaur service
#  systemd:
#    name: minotaur
#    enabled: true
