---
- name: install minotaur
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - minotaur

- name: install minotaur config
  template: 
    src: minotaur.conf.j2
    dest: /etc/minotaur.conf
    owner: root
    group: root
    mode: 0644

- name: create /var/log/minotaur
  file:
    path: /var/log/minotaur
    state: directory
    owner: minotaur
    group: minotaur
    mode: 0755

- name: install minotaur convenience commands
  copy:
    src: '{{ item.src }}'
    dest: '/usr/local/bin'
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: 'gs' }
    - { src: 'stats' }
    - { src: 'algos' }
    - { src: 'minlog' }
    - { src: 'gpustatdlog' }
    - { src: 'exclog' }
    - { src: 'excwraplog' }

- name: enable minotaur service
  systemd:
    name: minotaur
    enabled: true
